### PR TITLE
AISDK-57: Fix security vulnerabilities

### PR DESCRIPTION
**Pull request by k-weng**
Vulnerabilities found using `npm audit` and fixed using `npm audit fix`.

### CODE REVIEW

**Comment by JDongian** [comment]
Should we put this as a git hook or something? Or add it to the CI pipeline?

**Comment by k-weng** [comment]
Yeah we could add a script to Travis CI. There's a [npm package](https://www.npmjs.com/package/audit-ci) we could use. @kbridbur

**Comment by kbridbur** [comment]
I would rather not add it as an automatic step, it seems like something we should do manually. In this case it's fine since they're all dev dependencies but it seems like `npm audit fix` has no issue bumping major version numbers of dependencies which could theoretically cause a breaking change

**Review by kbridbur — APPROVED** [review]
:shipit: 

This PR looks good. Let's think a bit more about whether or not we want to automate dependency fixes

**Comment by k-weng** [comment]
@kbridbur Didn't mention this in the PR description but `npm audit fix` won't actually fix any vulnerabilities that require major version bumping unless you give it the option to. In addition, the npm package that I reference only fails the build if `npm audit` finds any vulns.

**Comment by kbridbur** [comment]
Ahh, I see. If that's the case then we should investigate adding a step like you guys are talking about to the CI pipeline. I'll file an issue

**Pull request merged**
